### ISSUE TITLE
Erratum page 24

### ISSUE THREAD

**Issue by wleftwich** [rasbt/machine-learning-book#10]
"It is important to note that the convergence of the perceptron is only guaranteed if the two classes
are linearly separable, which means that the two classes cannot be perfectly separated by a linear
decision boundary." 
s/cannot/can/

I'm a fan of previous editions -- looking forward to the new chapters on Pytorch.

**Comment by rasbt** [comment]
Wow, totally overlooked that, good catch. I just added it to the errata here: https://github.com/rasbt/machine-learning-book/tree/main/ERRATA
