### ISSUE TITLE
Chapter 11, p. 341 & 342

### ISSUE THREAD

**Issue by abojda** [rasbt/machine-learning-book#100]
Page 341
The formula for net input misses bias.

Page 342
![image](https://user-images.githubusercontent.com/9279773/207174929-c67472b6-7ebc-4eed-908e-e99b2f3dae5c.png)
I think this should be x^(in)`.

**Comment by rasbt** [comment]
Thanks, good catch! Will add a note to the errata to add the missing bias unit. The second one, in pg 342 was already fixed some time ago in a preprint I think: 

<img width="600" alt="Screenshot 2023-02-02 at 12 20 28 PM" src="https://user-images.githubusercontent.com/5618407/216412646-e6994d8a-0c31-45da-80fb-fbac4039ae1e.png">
