### ISSUE TITLE
Ch13: updates for torchmetrics Accuracy()

### ISSUE THREAD

**Issue by vmirly** [rasbt/machine-learning-book#105]
The current code in chapter 13 is for torchmetrics version torchmetrics 0.6.2
```python
        self.train_acc = Accuracy()
        self.valid_acc = Accuracy()
        self.test_acc = Accuracy()
```
works without any argument.

But in the latest version (0.11.0), the arguments `task` and `num_classes` are needed:
```python
        self.train_acc = Accuracy('multiclass', num_classes=10)
        self.valid_acc = Accuracy('multiclass', num_classes=10)
        self.test_acc = Accuracy('multiclass', num_classes=10)
```

Link to the notebook: https://github.com/rasbt/machine-learning-book/blob/main/ch13/ch13_part3_lightning.ipynb
Code lines: https://github.com/rasbt/machine-learning-book/blob/main/ch13/ch13_part3_lightning.py#L75-L77

**Comment by acmoudleysa** [comment]
Looks like it's fixed. There's still a minor issue in the code it seems. It should be `parse_version('0.8')` and not `parse_version(0.8)`.
