### ISSUE TITLE
Error: TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'(Chapter-13) 

### ISSUE THREAD

**Issue by andysingal** [rasbt/machine-learning-book#128]
Hey Sebastian,
      While running the code , i am getting the following error:
TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'

from pytorch_lightning.callbacks import ModelCheckpoint

```
mnistclassifier = MultiLayerPerceptron()

callbacks = [ModelCheckpoint(save_top_k=1, mode='max', monitor="valid_acc")] # save top 1 model

if torch.cuda.is_available(): # if you have GPUs
    trainer = pl.Trainer(max_epochs=10, callbacks=callbacks, gpus=1)
else:
    trainer = pl.Trainer(max_epochs=10, callbacks=callbacks)

trainer.fit(model=mnistclassifier, datamodule=mnist_dm)
```

code before that is the same as shared in your git repo.
Thanks,
Ankush Singal

**Comment by rasbt** [comment]
Hi there! In newer versions of torchmetrics it's now required to specify the task and number of classes. E.g., whereas it was

```python
acc = torchmetrics.Accuracy()
```

before, it's now

```python
acc = torchmetrics.Accuracy(task="multiclass", num_classes=10)
```

**Comment by rasbt** [comment]
Should be fixed now!
