### ISSUE TITLE
Chapter 14

### ISSUE THREAD

**Issue by AbdelrahimKoura** [rasbt/machine-learning-book#146]
To load dataset using this statement 
celeba_train_dataset = torchvision.datasets.CelebA(
 image_path, split='train',
 target_type='attr', download=True
 )
dataset can not load why?

**Comment by acmoudleysa** [comment]
https://drive.google.com/file/d/1m8-EBPgi5MRubrm6iQjafK2QMHDBMSfJ/view

Use this link.

**Comment by rasbt** [comment]
Sorry for the hassle here. It's a bit frustrating that it doesn't work out of the box via torchvision anymore.

This was also shared as an issue here: https://github.com/pytorch/vision/issues/1920

What I did is I downloaded the files from here: https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8?resourcekey=0-5BR16BdXnb8hVj6CNHKzLg

For simplicity, you can also use my link here where I already prepared the directory structure: https://drive.google.com/file/d/1m8-EBPgi5MRubrm6iQjafK2QMHDBMSfJ/view?usp=share_link

Download that zip file and place it in the `celeba` folder. Then unzip `img_align_celeba.zip`. And it should work:
<img width="1321" alt="Screenshot 2024-04-25 at 12 26 31 PM" src="https://github.com/rasbt/machine-learning-book/assets/5618407/34940bc3-dd9e-4d81-a0b3-811b275c8893">

Let me know in case it still doesn't work, and please feel free to reopen this issue then.
