### ISSUE TITLE
Chapter 11 Pg 361 - Incorrect Expression

### ISSUE THREAD

**Issue by jjtan** [rasbt/machine-learning-book#157]
$\frac{\partial}{\partial w_{j,l}^{(l)}} = L(W, b)$ should be $\frac{\partial L(W, b)}{\partial w_{j,l}^{(l)}}$

**Comment by rasbt** [comment]
Yes, good catch, and I agree. I have it in the errata here: https://github.com/rasbt/machine-learning-book/blob/main/ERRATA/README.md
