### ISSUE TITLE
Chapter 11 Page 366

### ISSUE THREAD

**Issue by z-3zh** [rasbt/machine-learning-book#160]
<img width="1163" alt="image" src="https://github.com/rasbt/machine-learning-book/assets/57746575/33f045b1-fdd7-4796-b8da-810860e4050d">
is it should be $\frac{\partial L}{\partial w_{1,1}^{(h)}}$ ?

**Comment by rasbt** [comment]
You are correct, and thanks for the note, just added it to the errata here and will update it in future reprints: #162
