### ISSUE TITLE
Chapter 15 pag. 505: Typo

### ISSUE THREAD

**Issue by miticollo** [rasbt/machine-learning-book#167]
I think there is a typo in the following computation
```math
\mathbf{o}^{\left( t \right)} = \sigma_{0}\left( \mathbf{W}_{ho}\mathbf{h}^{\left( t \right)}+\mathbf{b}_{0} \right)
```
I mean $`0`$ as subscript should be replaced with $`o`$:
```math
\mathbf{o}^{\left( t \right)} = \sigma_{o}\left( \mathbf{W}_{ho}\mathbf{h}^{\left( t \right)}+\mathbf{b}_{o} \right)
```
Anyway Figure 15.6 is correct.

**Comment by rasbt** [comment]
Thanks for the note, and I agree! I just added it to the Errata markdown file here: https://github.com/rasbt/machine-learning-book/tree/main/ERRATA#chapter-15
