### ISSUE TITLE
Downoading celeba dataset chapter 12 page 387.

### ISSUE THREAD

**Issue by sahlebrahim** [rasbt/machine-learning-book#172]
When I set (download = true) I get a MD5 checksum error and when I manually download it and put it in a folder I get a "dataset not found or corrupted".

**Comment by sahlebrahim** [comment]
> Arg, sorry about that. I saw some similar issues here and some users were able to resolve it. Have you tried the GDrive link from here? https://github.com/rasbt/machine-learning-book/discussions/54#discussioncomment-2667617
> 
> (In hindsight I really wish I had used a different dataset ...)
@rasbt 
still says dataset not found or corupted. Been stuck on this for days

**Comment by rasbt** [comment]
Let me know in case it still doesn't work, and please feel free to reopen this issue then.
