### ISSUE TITLE
RANSAC MAD definition/calculation (pages 286-287)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#18]
Hi Sebastian,
 
First of all, thank you for your brilliant work (books, videos, articles etc.)!
 
I’ve found that there is RANSAC description on the page 286 and MAD is mentioned as median absolute deviation (which corresponds to algorithm's description in sklearn's documentation).
However the code for MAD computation on the page 287 uses mean absolute deviation (function mean_absolute_deviation).
Is it correct?
 
Thank you.

**Comment by rasbt** [comment]
Thanks! Ha, that's a weird one. Not sure what I was thinking there ... 
Just updated the notebook and added this to the errata.
