### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append' for Pandas >=2

### ISSUE THREAD

**Issue by decorouz** [rasbt/machine-learning-book#182]
If you are like me, using the latest version of some of dependencies to follow along, there is a gotcha you should lookout for:
With Pandas 2.0+ release in April of 2023, Pandas deprecated the `. append()` method

https://github.com/rasbt/machine-learning-book/blob/af519a1aae331481ae3a22210d51fd40c37fdae0/ch08/ch08.py#L158

This line of code will through AttributeError. The work around is:
```py
...
new_row = pd.DataFrame({'review': [txt], 'sentiment': [labels[l]]})
df = pd.concat([df, new_row], ignore_index=True)
```

**Comment by rasbt** [comment]
Thanks for the note, and good catch. I had a fix for that in the notebook but totally missed applying it to the Python script as well. Should be fixed now. Thanks for the note!
