### ISSUE TITLE
Layer dimensions in NeuralNetMLP (page 348)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#23]
Hi Sebastian,

There are comments about dimensions for hidden and output layers for MLP on the page 348 and in the repository:
https://github.com/rasbt/machine-learning-book/blob/baf25131c3c0e1618bfde699bd6febb54a6f7240/ch11/neuralnet.py#L43-L45
https://github.com/rasbt/machine-learning-book/blob/baf25131c3c0e1618bfde699bd6febb54a6f7240/ch11/neuralnet.py#L49-L51

Based on the description on the same section above (page 342), it seems that:

- For hidden layer:
  - ``x`` has dimension ``[n_examples, n_features]`` (but ``[n_hidden, n_features]`` is specified)
  - ``self.weight_h.T`` has dimension ``[n_hidden, n_features].T`` (but ``[n_features, n_examples] .T`` is specified)

So ``z_h = np.dot(x, self.weight_h.T) + self.bias_h`` will have specified dimension (``[n_examples, n_hidden]``)

- For output layer:
``a_h`` has dimension ``[n_examples, n_hidden]`` (but ``[n_classes, n_hidden]`` is specified)
``self.weight_h.T`` has dimension ``[n_classes, n_hidden].T`` (but ``[n_hidden, n_examples] .T`` is specified)

So ``z_out = np.dot(a_h, self.weight_out.T) + self.bias_out`` will have specified dimension (``[n_examples, n_classes]``)

Is it correct, or I am wrong in comments interpretation?

Thank you.

**Comment by rasbt** [comment]
Oh, good call. think the code comments are still the old ones (arg, that's what I hate about code comments, sometimes it is easy to forget updating them). I initially had it as


    z_h = np.dot(self.weight_h, x.T).T + self.bias_h

instead of

    z_h = np.dot(x, self.weight_h.T) + self.bias_h

Both are equivalent, though. I will update this.
