### ISSUE TITLE
Partial derivatives notation (page 366)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#24]
Hi Sebastian,
 
Probably there are some inconsistencies in partial derivative formulas on page 366:
- On the picture with NN, there are 2 duplicated notations near the node <img src="https://render.githubusercontent.com/render/math?math=a_{2}^{(out)}"> - both have the same value <img src="https://render.githubusercontent.com/render/math?math=\partial{L}/\partial{a_{2}^{(out)}}">.
It seems that left notation will be equal to <img src="https://render.githubusercontent.com/render/math?math=\partial{a_{2}^{(out)}}/\partial{a_{1}^{(h)}}">?
- Subsequent 2 equations for the partial derivatives of the loss with respect to the first hidden layer weight have the left side equal to <img src="https://render.githubusercontent.com/render/math?math=\partial{L}/\partial{w_{1,1}^{(out)}}">.
Perhaps it is equal to <img src="https://render.githubusercontent.com/render/math?math=\partial{L}/\partial{w_{1,1}^{(h)}}">?
 
Thank you.

**Comment by rasbt** [comment]
You are right, thanks it should have been as shown below. Will add it to the errata.

![Screen Shot 2022-04-02 at 10 31 18 AM](https://user-images.githubusercontent.com/5618407/161390211-6792a582-b676-4bed-bd41-ecb6db1879dc.png)

**Comment by rasbt** [comment]
Done! Also fixed it in the notebook here: https://github.com/rasbt/machine-learning-book/blob/main/ch11/ch11.ipynb
