### ISSUE TITLE
AdaBoost duplicated update formula (page 233)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#26]
Hi Sebastian,
 
There is the same formula used for variables ``update_if_wrong_1`` and ``update_if_wrong_2`` on the page 233.
Also ``update_if_wrong_2`` is not mentioned in corresponding notebook/script in repository.
Probably this variable is not used anywhere?
 
Thank you.

**Comment by rasbt** [comment]
Ah, yes, right now it is


```
>>> update_if_wrong_1 = 0.1 * np.exp(-alpha_j * 1 * -1)
>>> print(update_if_wrong_1)
0.1527525231651947

>>> update_if_wrong_2 = 0.1 * np.exp(-alpha_j * 1 * -1)
>>> print(update_if_wrong_2)
0.1527525231651947
```

but the second one should have been

```
>>> update_if_wrong_2 = 0.1 * np.exp(-alpha_j * -1 * 1)
>>> print(update_if_wrong_2)
0.1527525231651947
```

**Comment by rasbt** [comment]
Added!
