### ISSUE TITLE
The optimal value of `C` (page 185)

### ISSUE THREAD

**Issue by ashwinshetgaonkar** [rasbt/machine-learning-book#27]
The pages says that the sweet spot is between `C =0.01 ` and `C=0.1` but as indicated in the preceding graph the max  test score occurs at` C=1`.

**Comment by rasbt** [comment]
Good point. It probably should have been 

>  In this case, the sweet spot appears to be between 0.1 and 1.0 of the C value.

instead of 

>  In this case, the sweet spot appears to be between 0.01 and 0.1 of the C value.

**Comment by rasbt** [comment]
Added it to the errata at https://github.com/rasbt/machine-learning-book/tree/main/ERRATA
