### ISSUE TITLE
Smile vs Gender classification (notebook ch14_part2.ipynb)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#30]
Hi Sebastian,
 
There is a description about gender classification in notebook ch14_part2.ipynb:
- ```Gender classification from face images using CNN```
- ```Training a CNN gender classifier```
 
But the code itself and the book section is about smile classification.
 
Thank you.

**Comment by rasbt** [comment]
Thanks for the note, my guess Hayden forgot to update the notebook. I will fix this

**Comment by rasbt** [comment]
Looked like it contained the updated code but just some headlines were still the old ones. Should be updated now. Thanks again!
