### ISSUE TITLE
Multilabel vs multiclass classification (page 400)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#35]
Hi Sebastian, 

There is the following statement on the page 400:
"Before we discuss what a hyperbolic tangent looks like, let’s briefly recapitulate some of the basics of
the logistic function and look at a generalization that makes it more useful for **multilabel** classification
problems."

The generalization that is mentioned after this section is about multiclass classification - did you mean multiclass, not multilabel classification and softmax function on this page?

Thank you.

**Comment by rasbt** [comment]
Wow yeah. I am usually super careful with the wording multiclass vs multilabel. This must have slipped through during editing somehow.

**Comment by rasbt** [comment]
Added it to the errata.
