### ISSUE TITLE
Embedding matrix dimension (page 519)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#36]
Hi Sebastian, 

There is the following statement on the page 519:
"The output will have the dimensionality batchsize × input_length × embedding_dim, where embedding_
dim is the size of the embedding features (here, set to **3**). The other argument provided to
the embedding layer, num_embeddings, corresponds to the unique integer values that the model will
receive as input (for instance, n + 2, set here to **10**). Therefore, the embedding matrix in this case has
the size **10×6**."

Based on these conclusions, probably there is a typo in the last sentence and embedding matrix dimension is 10x3?

Thank you.

**Comment by rasbt** [comment]
Good catch. It even says 3 in the code 😅

![Screen Shot 2022-04-13 at 6 27 02 PM](https://user-images.githubusercontent.com/5618407/163285894-9f1459b1-852d-40f4-ae0a-b5ea76b7ba6e.png)

**Comment by rasbt** [comment]
Added it to the errata
