### ISSUE TITLE
Missing text chunk (page 530)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#38]
Hi Sebastian, 

There is a code snippet for text preprocessing for language model on the page 530:
```
text_chunks = [text_encoded[i:i+chunk_size]
               for i in range(len(text_encoded)-chunk_size)]
```

Probably the last text chunk is not included, and to include all text chunks we need to use the following code:
```
text_chunks = [text_encoded[i:i+chunk_size]
               for i in range(len(text_encoded)-chunk_size+1)]
```
Then for the last ```i``` value (```len(text_encoded)-chunk_size)```) we will have text chunk:
```text_encoded[len(text_encoded)-chunk_size:len(text_encoded)]``` 
which has the size chunk_size and I suppose can be included as additional text chunk.

Thank you.

**Comment by rasbt** [comment]
Good catch. Yeah, the last elements are really just empty line characters so it wouldn't make any difference, but to be technically correct, the +1 is needed when I see it correctly.

**Comment by rasbt** [comment]
added to the Errata
