### ISSUE TITLE
Last convolutional layer's kernel dimension in discriminator network (page 617)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#43]
Hi Sebastian,
 
There is the description of the discriminator network for DCGAN on the page 617:
"The last convolutional layer uses kernels of **size 7×7** and a single filter to
reduce the spatial dimensionality of the output to 1×1×1."
 
Based on the picture of the discriminator, it seems that the last convolutional layer uses kernel of size 4×4.
Is it correct?
 
Thank you.

**Comment by rasbt** [comment]
good catch, thanks!
