### ISSUE TITLE
KL divergence formula for discrete distributions (page 626)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#44]
Hi Sebastian,
 
There are 2 formulas of KL divergence for discrete distributions on the page 626, and it seems the second formula has missing log transformation for the second multiplier (instead of P(x)/Q(x) it must be equal to log(P(x) / Q(x)).
 
Thank you.

**Comment by rasbt** [comment]
Ohh how could I miss that, thanks!! 🙈
