### ISSUE TITLE
Fully connected layer dimensions for GNN (p. 650)

### ISSUE THREAD

**Issue by labdmitriy** [rasbt/machine-learning-book#46]
Hi Sebastian,

There is a very useful picture on the page 650 with network layers description for GNN.
Probably that for fully connected layer the product W_fc (4x4) with h_fc (1x4) must be in swapped order (h_fc x W_fc) to get the same dimension as h_fc (1x4)?

Thank you.

**Comment by rasbt** [comment]
Just updated this, thanks!
