### ISSUE TITLE
Make an optional flowchart

### ISSUE THREAD

**Issue by rasbt** [rasbt/machine-learning-book#56]
> Suggestion : I would recommend and suggest that the author do a flowchart or a diagram for all steps from chapter 1 to 6 for each Machine learning algorithm or all of them at once. like for example some machine learning algorithm don't need to preprocess data ( standardized for example Like tree algorithm  ) this will help new learners like me to memorize all required steps fast starting from preprocessing data till tuning and evaluating. This will help us to achieve and done a perfect machine learning model.

**Comment by OmarAlmighty** [comment]
Hi, Sebastian

I would like to contribute to creating the flowcharts for the algorithms. Here is a simple diagram for the **Perceptron learning rule** which is provided in chapter 2.

![m](https://user-images.githubusercontent.com/47993441/195851309-f33626ec-3b20-4827-90a5-e8ce4ac18bdc.png)

**Please let me know if you are interested so we can work together.**

**Comment by rasbt** [comment]
Hi @OmarAlmighty, thanks for creating this! I'd say this definitely captures the essence of the perceptron algorithm. However, at the same time, it's also similar to Adaline (and almost similar to logistic regression). Now, thinking about some more complicated learning algorithms, I wonder if it is feasible to create flowcharts for them this way ...

If you find it helpful to create these flowcharts, I am open to collect them in a "contributed" or "community" folder. Maybe "machine-learning-book/contributed/algorithm-flowcharts". I'd be happy to share it on social media and showcase the contributions. But now pressure creating those. Looks like it would be lots of work.

**Comment by OmarAlmighty** [comment]
Hi @rasbt, thanks for your feedback. I will start working on them ASAP. But how should I submit them to you? What method best works for you; should I send them via email or post them in a comment? 

Also, it would be great if I get feedback about the flowcharts when I submit them to ensure the validity of the diagram and that it captures the essence of the algorithm.
