### ISSUE TITLE
Downloading CelebA dataset from book's download link.

### ISSUE THREAD

**Issue by Mahyar24** [rasbt/machine-learning-book#57]
On page 483, one way to download the CelebA dataset is with the book's download link. 
In the instructions, you mentioned that we must unzip the downloaded file. But one step that is missing is that we have to unzip the `img_align_celeba.zip` too; otherwise, PyTorch will throw an error complaining the dataset is corrupt, which is caused by this line of code:

https://github.com/pytorch/vision/blob/22400011d6a498ecf77797a56dfe13bc94c426ca/torchvision/datasets/celeba.py#L142

So, I think it's better to mention that explicitly too.  

P.S: Thanks for this excellent book!

**Comment by rasbt** [comment]
Thanks a lot for the note! Let me test this again and then update the notebook :)!

**Comment by rasbt** [comment]
Alright, just added a note via #59. Thanks again for pointing it out!
