### ISSUE TITLE
Running on Colab requires another import

### ISSUE THREAD

**Issue by Shuaf98** [rasbt/machine-learning-book#58]
When running on Colab, notebook 15.2 requires a pipinstall torchdata in addition to the pip install torchtext in otder to import the IMDB dataset.

**Comment by rasbt** [comment]
Thanks for the note! Huh, that's interesting. In my case, I can import IMDB directly from torchtext without torchdata:
![Screen Shot 2022-05-05 at 9 04 48 AM](https://user-images.githubusercontent.com/5618407/166941003-9adb4c19-4cc7-46e2-b95d-a95d97b21564.png)

What version of torchtext does your Colab environment have installed? I currently have `'0.11.2'` where this works without torchdata.

**Comment by rasbt** [comment]
Thanks! It does seem to work fine for me in Colab with 0.12.0 too though. That's kind of weird �
![Screen Shot 2022-05-05 at 11 40 25 AM](https://user-images.githubusercontent.com/5618407/166971617-97ee1a16-2363-4f7f-80bb-161c30e6df82.png)
�

**Comment by rasbt** [comment]
Please let me know in case the problem still persists

**Comment by Shuaf98** [comment]
Hi, only seeing this now. I see the thread is closed, however. I wasn't
able to check again, as both packages are already installed onto Colab.
More than happy to help, if you have another idea as to how I can validate
it.

Regards,

Shua Friedman
058-663-5362
***@***.***
