### ISSUE TITLE
Possible error in ch14_part2.ipynb of GitHub

### ISSUE THREAD

**Issue by Unamu7simure** [rasbt/machine-learning-book#62]
There is a code  'get_smile = lambda attr: attr[18]' in In[6] cell.
It should be 'get_smile = lambda attr: attr[31]' according to the  'list_attr_celeba' text document in the celeba file.

**Comment by rasbt** [comment]
Wow, big oversight! I have a "correct" smile classifier here (https://github.com/rasbt/deeplearning-models/blob/master/pytorch_ipynb/cnn/cnn-vgg16-celeba.ipynb) and am not sure how that happened. Will fix that. Thanks a lot for pointing that out!

**Comment by rasbt** [comment]
Just updated it via #63. Thanks again!
