### ISSUE TITLE
Typo on Page 38?

### ISSUE THREAD

**Issue by claudio525** [rasbt/machine-learning-book#64]
I think there is a typo in the last line of the screenshot (bottom of page 38); shouldn't the summation on the right be over the weights/inputs, i.e. $j$ instead of $i$ (training samples)?

<img width="824" alt="Screen Shot 2022-06-07 at 16 18 43" src="https://user-images.githubusercontent.com/45545396/172295078-f2ee9ada-d157-4f3f-a8e0-54d822a044c9.png">

**Comment by rasbt** [comment]
You are absolutely right, it should be 

$$\sum_j w_j x^{(i)}_{j} + b$$

Will add it to the errata. Thanks for posting!
