### ISSUE TITLE
Chapter 15 code typos.

### ISSUE THREAD

**Issue by ksmith3372** [rasbt/machine-learning-book#67]
I ran across another couple of typos in the book. The  Jupyter notebook with the data is correct. Chapter 15, page 508, 2nd code block, line 12 is missing the closing bracket.   Chapter 15, page 508, 2nd code block, line 11 should be b_xh rather than b_hh.

**Comment by rasbt** [comment]
Thanks for taking the time to post these! They are now in the errata.
