### ISSUE TITLE
P. 458 bracket should be corrected to floor oepration

### ISSUE THREAD

**Issue by hongsoog** [rasbt/machine-learning-book#72]
In Page 458, 

In the following paragraph at the bottom of page, 

Consider the following two cases:
* Compute the output size for an input vector of size 10 with a convolution kernel of size 5, padding 2, and stride 1:  

$$ n=10, m=5, p=2, s=1 \to o = \left [ \frac{10 + 2 \times 2 - 5}{1} \right ] +1 = 10 $$  

(Note that in this case, the output size turns out to be the same as the input; therefore, we can conclude this to be same padding mode.)  
* How does the output size change for the same input vector when we have a kernel of size 3 and stride 2?  

$$ n=10, m=3, p=2, s=2 \to o = \left [ \frac{10 + 2 \times 2 - 3}{2} \right ] +1 = 6 $$

should be corrected right floor symbole as follows:
Consider the following two cases:
* Compute the output size for an input vector of size 10 with a convolution kernel of size 5, padding 2, and stride 1:  

$$ n=10, m=5, p=2, s=1 \to o = \left \lfloor \frac{10 + 2 \times 2 - 5}{1} \right \rfloor +1 = 10 $$  

(Note that in this case, the output size turns out to be the same as the input; therefore, we can conclude this to be same padding mode.)  

* How does the output size change for the same input vector when we have a kernel of size 3 and stride 2?  

$$ n=10, m=3, p=2, s=2 \to o = \left \lfloor \frac{10 + 2 \times 2 - 3}{2} \right \rfloor +1 = 6 $$

**Comment by rasbt** [comment]
Oh yes, 100%. This looks correct in my drafts. I think what happened was that the layouter thought the top part was cut off and replaced the floor symbol by regular brackets 😅. Thanks for sending that in!
