### ISSUE TITLE
P. 477 formula should be corrected with right floor symbol

### ISSUE THREAD

**Issue by hongsoog** [rasbt/machine-learning-book#73]
In page 477. The formula for spatial dimension of output feature map

$$
o = \left [ \frac{n + 2p -m}{s} \right ] + 1
$$

should be corrected with right floor symbol as follows:

$$
o = \left \lfloor \frac{n + 2p -m}{s} \right \rfloor + 1
$$

**Comment by rasbt** [comment]
Thanks again! also just added it to the errata!
