### ISSUE TITLE
Chapter 15 minor typo

### ISSUE THREAD

**Issue by harrybaines** [rasbt/machine-learning-book#81]
Loving the book so far! Just found a small typo on page 506:

<img width="808" alt="Screenshot 2022-09-16 at 13 22 39" src="https://user-images.githubusercontent.com/11751531/190637860-605d707b-5261-4e78-a345-d055f96746e0.png">

The $W_{hy}$ term in the final output equation should be $W_{ho}$ I think.

**Comment by rasbt** [comment]
Thanks a lot! Just fixed it in the notebook!
