### ISSUE TITLE
ch4 pag 120

### ISSUE THREAD

**Issue by GianniGi** [rasbt/machine-learning-book#82]
The formula at the bottom
should have the (i) index also for the letters mu_x and sigma_x.

`x_std(i) = x(i) - mu_x(i) / sigma(x)(i)`

**Comment by rasbt** [comment]
Yeah, that could technically be added. I think I omitted it because of the other subscripts and because it looked a bit overcrowded (overcomplicated). On the next page I am mentioning that it's a particular feature column.
