### ISSUE TITLE
Code Bug in the Page 397

### ISSUE THREAD

**Issue by DataPsycho** [rasbt/machine-learning-book#93]
Hi,
IN the page 397 while training a Model as follows:

```python
batch_size = 2
num_epochs = 100
loss_hist = [0] * num_epochs
accuracy_hist = [0] * num_epochs

for epoch in range(num_epochs):
    for x_batch, y_batch in train_dl:
        pred = model(x_batch)
        loss = loss_fn(pred, y_batch)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        loss_hist[epoch] += loss.item() * y_batch.size(0)
        is_correct = (torch.argmax(pred, dim=1) == y_batch).float()
        accuracy_hist[epoch] += is_correct.mean()
    loss_hist[epoch] /= len(train_dl.dataset)
    accuracy_hist[epoch] /= len(train_dl.dataset)

plt.plot(accuracy_hist, lw=3)
```
here batch size is 2 so there will be 50 inner cycle and 100 epoch for each cycle. In side the inner cicyle `is_correct.mean()` does not looks correct, it should be `is_correct.sum()` otherwise ` accuracy_hist[epoch] /= len(train_dl.dataset)` needed to be cut half  `accuracy_hist[epoch] /= len(train_dl.dataset)/2` as you already have averaged before 2 values into one.

**Comment by rasbt** [comment]
Thanks for the note and sorry for the confusion! I believe this is something that I adjusted here in the code a while back: https://github.com/rasbt/machine-learning-book/blob/main/ch12/ch12_part2.py#L295 

Will have the publisher update the  book version as well this week! Thanks!
