### ISSUE TITLE
chapter 14 pag.489 transforms

### ISSUE THREAD

**Issue by g-i-o-r-g-i-o** [rasbt/machine-learning-book#94]
Hello, I don't know if I was the only one not getting this the first time that I read it, but I didn't notice that "transform trains" are applied to the full DataSet each time that it's reloaded, for each epoch. Probably because the line where the dataset is reloaded, is completely different from the usual one, which is more legible.

I would change the red line:
![image](https://user-images.githubusercontent.com/9282332/202165639-ca4f7988-9502-44ac-b227-e0e89f4d770b.png)
![image](https://user-images.githubusercontent.com/9282332/202165096-a0cb2f2f-92f6-4124-a4ef-9eb915fefa43.png)
to this:
![image](https://user-images.githubusercontent.com/9282332/202165824-511ee37a-2733-43be-a2d2-f1216462193a.png)

so the code becomes more legible and familiar??

```
from torch.utils.data import DataLoader

celeba_train_dataset = torchvision.datasets.CelebA(image_path, 
                                                   split='train', 
                                                   target_type='attr', 
                                                   download=False, 
                                                   transform=transform_train,
                                                   target_transform=get_smile)

torch.manual_seed(1)
data_loader = DataLoader(celeba_train_dataset, batch_size=2)

fig = plt.figure(figsize=(15, 6))

num_epochs = 5
for j in range(num_epochs):
    for img_batch, label_batch in data_loader: # new line
        img = img_batch[0]
        ax = fig.add_subplot(2, 5, j + 1)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_title(f'Epoch {j}:', size=15)
        ax.imshow(img.permute(1, 2, 0))
    
        img = img_batch[1]
        ax = fig.add_subplot(2, 5, j + 6)
        ax.set_xticks([])
        ax.set_yticks([])
        ax.imshow(img.permute(1, 2, 0))
        break #new break
        
      
    
#plt.savefig('figures/14_16.png', dpi=300)
plt.show()
```

**Comment by rasbt** [comment]
Totally agree. That's also how I usually write it. Not sure why we did it differently here @haydenliu?

**Comment by haydenliu** [comment]
Hey @GianniGi @rasbt 
You are right, "for img_batch, label_batch in data_loader" is enough.
